// Generated by CodiumAI
import { render } from "@testing-library/react";
import Tooltip from "@/components/ui/Tooltip";

describe("Skills", () => {
  // Tooltip should render children correctly when provided
  it("should render children correctly when provided", () => {
    const { getByText } = render(<Tooltip>Test Child</Tooltip>);
    expect(getByText("Test Child")).toBeInTheDocument();
  });
});
